export const selectors = {
  usernameInput: "[name='user-name']",
  passwordInput: "[name='password']",
  submitButton: "[type='submit']",
  addToCartBackpack: '[data-test="add-to-cart-sauce-labs-backpack"]',
  addToCartBikeLight: '[data-test="add-to-cart-sauce-labs-bike-light"]',
  addToCartBoltTshirt: '[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]',
  cartLink: '[data-test="shopping-cart-link"]',
  checkoutButton: '[data-test="checkout"]',
  firstNameInput: '[data-test="firstName"]',
  lastNameInput: '[data-test="lastName"]',
  postalCodeInput: '[data-test="postalCode"]',
  continueButton: '[data-test="continue"]',
  finishButton: '[data-test="finish"]',
  backToProductsButton: '[data-test="back-to-products"]',
  productSortContainer: ".product_sort_container",
  addToCartFleeceJacket: '[data-test="add-to-cart-sauce-labs-fleece-jacket"]',
  removeBackpack: '[data-test="remove-sauce-labs-backpack"]',
  removeBikeLight: '[data-test="remove-sauce-labs-bike-light"]',
  removeBoltTshirt: '[data-test="remove-sauce-labs-bolt-t-shirt"]',
  continueShoppingButton: '[data-test="continue-shopping"]'
};
